from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    OPERATOR = "OPERATOR"
    VIEWER = "VIEWER"


class ProjectStatus(str, Enum):
    PLANNED = "PLANNED"
    ACTIVE = "ACTIVE"
    ON_HOLD = "ON_HOLD"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class BillingStatus(str, Enum):
    NOT_INVOICED = "NOT_INVOICED"
    PARTIALLY_INVOICED = "PARTIALLY_INVOICED"
    FULLY_INVOICED = "FULLY_INVOICED"


class CollectionStatus(str, Enum):
    NOT_DUE = "NOT_DUE"
    PARTIALLY_PAID = "PARTIALLY_PAID"
    PAID = "PAID"
    OVERDUE = "OVERDUE"


class WorkflowStatus(str, Enum):
    CAPTURED = "CAPTURED"
    EXTRACTED = "EXTRACTED"
    STAGED = "STAGED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    POSTED = "POSTED"
    RECONCILED = "RECONCILED"
    REVERSED = "REVERSED"


class ReviewFlag(str, Enum):
    OCR_LOW_CONFIDENCE = "OCR_LOW_CONFIDENCE"
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    DUPLICATE_SUSPECTED = "DUPLICATE_SUSPECTED"
    PROJECT_UNKNOWN = "PROJECT_UNKNOWN"
    VENDOR_UNKNOWN = "VENDOR_UNKNOWN"
    CUSTOMER_UNKNOWN = "CUSTOMER_UNKNOWN"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    DATE_MISMATCH = "DATE_MISMATCH"
    TAX_REVIEW = "TAX_REVIEW"
    ACCOUNT_REVIEW = "ACCOUNT_REVIEW"
    RELATED_PARTY_REVIEW = "RELATED_PARTY_REVIEW"


class TransactionType(str, Enum):
    # Direct & Bills
    DIRECT_PURCHASE = "DIRECT_PURCHASE"
    VENDOR_BILL = "VENDOR_BILL"
    PAY_VENDOR_BILL = "PAY_VENDOR_BILL"
    SUBCONTRACTOR_BILL = "SUBCONTRACTOR_BILL"
    PAY_SUBCONTRACTOR = "PAY_SUBCONTRACTOR"

    # Advances & Settlements
    VENDOR_ADVANCE = "VENDOR_ADVANCE"
    SETTLE_VENDOR_ADVANCE = "SETTLE_VENDOR_ADVANCE"
    EMPLOYEE_ADVANCE = "EMPLOYEE_ADVANCE"
    EMPLOYEE_SETTLEMENT = "EMPLOYEE_SETTLEMENT"
    CUSTOMER_ADVANCE = "CUSTOMER_ADVANCE"

    # Reimbursements & Petty Cash
    REIMBURSEMENT = "REIMBURSEMENT"
    PAY_REIMBURSEMENT = "PAY_REIMBURSEMENT"
    PETTY_CASH_EXPENSE = "PETTY_CASH_EXPENSE"
    TOPUP_PETTY_CASH = "TOPUP_PETTY_CASH"
    RETURN_PETTY_CASH = "RETURN_PETTY_CASH"

    # Transfers
    BANK_TO_CASH = "BANK_TO_CASH"
    CASH_TO_BANK = "CASH_TO_BANK"
    INTERBANK_TRANSFER = "INTERBANK_TRANSFER"

    # Assets & Inventory
    ASSET_PURCHASE = "ASSET_PURCHASE"
    INVENTORY_PURCHASE = "INVENTORY_PURCHASE"
    INVENTORY_USAGE = "INVENTORY_USAGE"

    # Customer Billing & Revenue
    CUSTOMER_INVOICE = "CUSTOMER_INVOICE"
    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"
    RETENTION_RELEASE = "RETENTION_RELEASE"
    REVENUE_RECOGNITION = "REVENUE_RECOGNITION"

    # Refunds
    CUSTOMER_REFUND = "CUSTOMER_REFUND"
    VENDOR_REFUND = "VENDOR_REFUND"

    # Equity & Financing
    OWNER_CONTRIBUTION = "OWNER_CONTRIBUTION"
    OWNER_WITHDRAWAL = "OWNER_WITHDRAWAL"
    LOAN_RECEIVED = "LOAN_RECEIVED"
    LOAN_PAYMENT = "LOAN_PAYMENT"

    # Overhead & Adjustments
    BANK_CHARGE = "BANK_CHARGE"
    OTHER_INCOME = "OTHER_INCOME"
    OTHER_EXPENSE = "OTHER_EXPENSE"
    JOURNAL_ADJUSTMENT = "JOURNAL_ADJUSTMENT"
    REVERSAL = "REVERSAL"


class CostCategory(str, Enum):
    MAT = "MAT"  # Material & Goods
    SUB = "SUB"  # Subcontractor
    LAB = "LAB"  # Direct Labor / Technicians
    TRN = "TRN"  # Local Transportation & Fuel
    TRV = "TRV"  # Travel & Lodging
    LOG = "LOG"  # Logistics & Freight
    EQP = "EQP"  # Equipment Rental
    SIT = "SIT"  # Site & Safety Expense
    OTH = "OTH"  # Other Direct Costs


class ExpenseCategory(str, Enum):
    SALARY = "SALARY"
    FEE = "FEE"
    OFFICE_ADMIN = "OFFICE_ADMIN"
    TRAVEL_OFFICE = "TRAVEL_OFFICE"
    PERMITS = "PERMITS"
    PROFESSIONAL_SERVICE = "PROFESSIONAL_SERVICE"
    BANK_CHARGES = "BANK_CHARGES"
    DEPRECIATION = "DEPRECIATION"
    OTHER_OPERATIONAL = "OTHER_OPERATIONAL"


class AccountType(str, Enum):
    ASSET = "ASSET"
    LIABILITY = "LIABILITY"
    EQUITY = "EQUITY"
    REVENUE = "REVENUE"
    EXPENSE = "EXPENSE"


class NormalBalance(str, Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class DocumentType(str, Enum):
    # Contracts
    PO_CUSTOMER = "PO_CUSTOMER"
    SPK = "SPK"
    CONTRACT = "CONTRACT"
    VARIATION_ORDER = "VARIATION_ORDER"

    # Procurement
    PURCHASE_ORDER = "PURCHASE_ORDER"
    QUOTATION = "QUOTATION"
    VENDOR_INVOICE = "VENDOR_INVOICE"
    SUBCONTRACT_AGREEMENT = "SUBCONTRACT_AGREEMENT"

    # Payment
    TRANSFER_PROOF = "TRANSFER_PROOF"
    RECEIPT = "RECEIPT"
    BANK_STATEMENT = "BANK_STATEMENT"
    PETTY_CASH_PROOF = "PETTY_CASH_PROOF"

    # Project Evidence
    SURAT_JALAN = "SURAT_JALAN"
    BAST = "BAST"
    PROGRESS_REPORT = "PROGRESS_REPORT"
    TIMESHEET = "TIMESHEET"

    # Billing
    CUSTOMER_INVOICE = "CUSTOMER_INVOICE"
    CUSTOMER_RECEIPT = "CUSTOMER_RECEIPT"

    # Tax
    TAX_INVOICE = "TAX_INVOICE"
    WITHHOLDING_DOCUMENT = "WITHHOLDING_DOCUMENT"
    OTHER_TAX_DOCUMENT = "OTHER_TAX_DOCUMENT"
    UNKNOWN = "UNKNOWN"


class DocumentProcessingStatus(str, Enum):
    UPLOADED = "UPLOADED"
    HASHED = "HASHED"
    EXTRACTING = "EXTRACTING"
    EXTRACTED = "EXTRACTED"
    MATCHING = "MATCHING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"


class DocumentSourceChannel(str, Enum):
    WEB = "WEB"
    API = "API"


class CandidateStatus(str, Enum):
    PROPOSED = "PROPOSED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    CONVERTED = "CONVERTED"
